created google login and did bug fixes
kalviumcommunity/Dopster pull request #9
Opened 2023-03-14 07:17 UTC by ayushkumar2808

2023-03-14 11:47 UTC, PatelNeelMahesh requested changes
After doing required changes you can merge pull request.

2023-03-14 11:47 UTC, PatelNeelMahesh commented on client/src/components/pages/GoogleAuth.js
> +        "382413014720-hc9v4e6gnh52giikp9u6f0qa79qj0f11.apps.googleusercontent.com",
You might want to add client_id in .env file.

2023-03-14 11:47 UTC, PatelNeelMahesh commented on server/routes/auth.js
> +const client = new OAuth2Client("382413014720-hc9v4e6gnh52giikp9u6f0qa79qj0f11.apps.googleusercontent.com");
Get variable from .env

2023-03-15 03:59 UTC, ayushkumar2808 commented on client/src/components/pages/GoogleAuth.js
> +        "382413014720-hc9v4e6gnh52giikp9u6f0qa79qj0f11.apps.googleusercontent.com",
ok, I will add it.

2023-03-15 04:10 UTC, merged